### PR TITLE
Get PORT env var from envVarsSchema instead of process.env

### PR DESCRIPTION
**Pull request by kronicka**
It ain't much, but it's honest work.

### CODE REVIEW

**Comment by nopeless** [comment]
ur work does not work as intended. pls fix

**Comment by kronicka** [comment]
> ur work does not work as intended. pls fix

I lied about the work being honest. *cough*

**Comment by nopeless** [comment]
error message does not fit the context

@kronicka

**Comment by nopeless** [comment]
@kronicka since CI passed, I'm deleting ur branch. for the read me edits, pls make another branch. if u need help with rebasing just dm me

**Pull request merged**
